// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkVm91gvYaiY3M_N4ozpmCByVn7am7MHA',
    appId: '1:570102492776:web:9c4b7f0973d9db57b695dd',
    messagingSenderId: '570102492776',
    projectId: 'money-tracker-362f8',
    authDomain: 'money-tracker-362f8.firebaseapp.com',
    storageBucket: 'money-tracker-362f8.firebasestorage.app',
    measurementId: 'G-D8S75EDP5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTNOCKpPMp2TbLCvkgjeBhuKuqlTt4yIs',
    appId: '1:570102492776:android:1f646529bbecab29b695dd',
    messagingSenderId: '570102492776',
    projectId: 'money-tracker-362f8',
    storageBucket: 'money-tracker-362f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoA40ZQaX_FKRjw-9jcE-x99RdDGcJ4Gc',
    appId: '1:570102492776:ios:baa480b06babc7d7b695dd',
    messagingSenderId: '570102492776',
    projectId: 'money-tracker-362f8',
    storageBucket: 'money-tracker-362f8.firebasestorage.app',
    iosBundleId: 'com.example.moneytracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoA40ZQaX_FKRjw-9jcE-x99RdDGcJ4Gc',
    appId: '1:570102492776:ios:baa480b06babc7d7b695dd',
    messagingSenderId: '570102492776',
    projectId: 'money-tracker-362f8',
    storageBucket: 'money-tracker-362f8.firebasestorage.app',
    iosBundleId: 'com.example.moneytracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkVm91gvYaiY3M_N4ozpmCByVn7am7MHA',
    appId: '1:570102492776:web:f4ef2e638aeb1d40b695dd',
    messagingSenderId: '570102492776',
    projectId: 'money-tracker-362f8',
    authDomain: 'money-tracker-362f8.firebaseapp.com',
    storageBucket: 'money-tracker-362f8.firebasestorage.app',
    measurementId: 'G-EHJH46QM0D',
  );
}
